const data = [
    {
        name:"友情链接",
        link:[
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            },
            {
                name:"龙轩导航",
                url:"http://ilxdh.com/"       
            }
        ]
    },
    {
        name:'关于我们',
        link:[
            {
                name:'简介',
                url:"http://ilxdh.com/about.html"
            },
            {
                name:"@龙轩日常",
                url:'http://ilxdh.com/'
            },
            {
                name:"@龙轩日常",
                url:'http://ilxdh.com/'
            },
            {
                name:"@龙轩日常",
                url:'http://ilxdh.com/'
            },
            {
                name:"@龙轩日常",
                url:'http://ilxdh.com/'
            }
        ]
    },
    {
        name:"关于网站",
        link:[
            {
                name:"开源地址",
                url:""
            },
            {
                name:"链接提交",
                url:""
            },
            {
                name:"网站调查问卷",
                url:""
            }
        ]
    }
]
export default data;