const data = [
    {
        name:"网页",
        desc:'搜索你想要的网页吧',
        link:[
            {
                name:"百度",
                link:"https://www.baidu.com/s?wd="
            },
            {
                name:"谷歌镜像",
                link:"https://9shi.ml/search?q=",
            },
            {
                name:"必应",
                link:"https://www.bing.com/search?q="
            },
            {
                name:"知乎",
                link:"https://www.zhihu.com/search?type=content&q="
            },
            {
                name:"搜狗",
                link:"https://www.sogou.com/web?query="
            },
            {
                name:"微信",
                link:"http://weixin.sogou.com/weixin?type=2&query="
            }
        ]
    },
    {
        name:"影视",
        desc:'美美的看上一场电影吧',
        link:[
            {
                name:"疯狂影视搜索",
                link:"http://ifkdy.com/?q="
            },
            {
                name:"哔哩哔哩",
                link:"https://search.bilibili.com/all?keyword="
            },
            {
                name:"降龙影院",
                link:"http://xlyy100.com/index.php?m=vod-search-pg-1-wd-"
            },
            {
                name:"胖鸟影院",
                link:"http://www.pniao.com/Mov/so/"
            },
            {
                name:"动漫花园",
                link:"https://share.dmhy.org/topics/list?keyword="
            }
        ]
    },
    {
        name:"网盘",
        desc:'你想要的这里都有 ',
        link:[
            {
                name:"58网盘",
                link:"http://www.58wangpan.com/search/kw"
            },
            {
                name:"去转盘",
                link:"http://www.quzhuanpan.com/source/search.action?q="
            },
            {
                name:'特百度',
                link:'https://www.ttyunsou.com/s?keyword='
            }
        ]
    },
    {
        name:"软件",
        desc:'下面目录推荐软件，可以试试',
        link:[
            {
                name:"胡萝卜周",
                link:"http://www.carrotchou.blog/?s="
            },
            {
                name:'吾爱破解',
                link:'http://zhannei.baidu.com/cse/search?click=1&s=14525262514411293706&isNeedCheckDomain=1&jump=1&q='
            },
            {
                name:'百度软件中心',
                link:'http://rj.baidu.com/search/index/?kw='
            },
            {
                name:"pc6",
                link:"https://s.pc6.com/cse/search?s=12026392560237532321&q="
            },
            {
                name:"下载吧",
                link:"http://zhannei.baidu.com/cse/search?s=9035802123405734980&q="
            }
        ]
    },
    {
        name:"学术",
        desc:'',
        link:[
            {
                name:"中国学术",
                link:"http://www.sciinfo.cn/Result.aspx?c=1&q=神帝&t=1&l=allLan&sq="
            },
            {
                name:"golo学术",
                link:"https://xs.glgoo.net/scholar?hl=zh-CN&q="
            },
            {
                name:"必应学术",
                link:"https://www.bing.com/academic/search?q="
            },
            {
                name:"谷歌学术",
                link:"https://xs.glgoo.net/scholar?hl=zh-CN&q="
            }
        ]
    },
    {
        name:"音乐",
        desc:'动听的音乐可以陶冶情操',
        link:[
            {
                name:"网易云",
                link:"http://music.163.com/#/search/m/?s="
            },
            {
                name:"QQ音乐",
                link:"https://y.qq.com/portal/search.html#page=1&searchid=1&remoteplace=txt.yqq.top&t=song&w="
            },
            {
                name:'音悦台',
                link:'http://so.yinyuetai.com/?keyword='
            },
            {
                name:'酷狗',
                link:'http://www.kugou.com/yy/html/search.html#searchType=song&searchKeyWord='
            }
        ]
    },
    {
        name:"电子书",
        desc:'搜索你想要的网页吧',
        link:[
            {
                name:"Gitbook",
                link:"https://www.gitbook.com/search?q="
            },
            {
                name:"鸠摩搜书",
                link:"https://www.jiumodiary.com/?"
            },
            {
                name:'笔趣阁',
                link:'https://www.qu.la/book/14721/?keyword='
            }
        ]
    },
    {
        name:"课程",
        desc:'搜索你想要的网页吧',
        link:[
            {
                name:"慕课网",
                link:"https://www.imooc.com/search/?words="
            },
            {
                name:"MooC",
                link:"https://www.icourse163.org/search.htm?search="
            },
            {
                name:"网易云课堂",
                link:"http://study.163.com/courses-search?keyword="
            },
            {
                name:"实验楼",
                link:"https://www.shiyanlou.com/search?search="
            },
            {
                name:'网易公开课',
                link:'https://c.open.163.com/search/search.htm?query='
            }
        ]
    }
]
export default data;
